const FARMS={Strathdee:{"1":4.90,"2":4.80,"3":4.80,"4":4.80,"5":4.70,"6":4.70,"7":4.70,"8":4.70,"9T":2.80,"9B":4.61,"10B":4.65,"School 1":4.07,"School 2":3.73,"Gully 1":5.23},Rays:{"1":5.10,"2":5.10,"3":5.10,"4":5.10,"5":5.10,"6":5.10,"7":3.40,"8":3.40},Tavasci:{"1":4.50,"2":4.50,"3":4.50,"4":4.50,"5":4.50,"6":4.50,"7":4.50,"8":5.12,"9":1.70,"10":0.74},Zanetti:{"1":4.80,"2":4.80,"3":4.80,"4":4.80,"5":4.80,"6":6.15},Menso:{"1":4.14,"2":4.01,"3":3.82,"4":3.42,"5":2.95,"6":4.54,"7":4.14},"Norris Back":{"1":3.75,"2":4.50,"3":4.50,"4":4.50,"School 1":4.20,"School 2":4.20,"School 3":4.80,Gully:2.55},Jacks:{"1":4.30,"2":3.20,"3":4.60,"4":4.60,"5":2.80,"5A":1.50,"6":3.90,"7":4.60,"8":4.60,"9":4.60}};
const KEY="irrigationFertigationPlannerV1",QKEY="quickRuntimePlannerSetupV2",$=x=>document.getElementById(x);let saved={};try{saved=JSON.parse(localStorage.getItem(KEY)||"{}")||{}}catch(e){};let qsetup={};try{qsetup=JSON.parse(localStorage.getItem(QKEY)||"{}")||{}}catch(e){};let chosen=new Set();let injectionOrder=[];

const EXCEL_PRESETS={
  Jacks:[
    {name:"Jacks Shed Fertigation 1",type:"vat",flow:10.7,product:"Calcium Nitrate",solution:1500,preflow:5,rinse:30},
    {name:"Jacks Shed Fertigation 2",type:"direct",flow:10.8,product:"Cal 40",solution:140,preflow:5,rinse:0},
    {name:"Jacks Shed Fertigation 3",type:"direct",flow:5.3,product:"Optical AG",solution:140,preflow:5,rinse:0},
    {name:"Jacks Shed Flush",type:"flush",flow:0,product:"",solution:0,preflow:5,rinse:10}
  ],
  Tavasci:[
    {name:"Tavasci Injector 1",type:"vat",flow:9.5,product:"Calcium Nitrate",solution:1500,preflow:5,rinse:30},
    {name:"Tavasci Injector 2",type:"direct",flow:5.8,product:"",solution:220,preflow:5,rinse:0},
    {name:"Tavasci Injector 3",type:"direct",flow:1,product:"",solution:300,preflow:5,rinse:0},
    {name:"Tavasci Flush",type:"flush",flow:0,product:"",solution:0,preflow:5,rinse:10}
  ],
  Zanetti:[
    {name:"Zanetti Injector 1",type:"vat",flow:15.6,product:"Calcium Nitrate",solution:1500,preflow:5,rinse:30},
    {name:"Zanetti Injector 2",type:"direct",flow:4.6,product:"Optical AG",solution:220,preflow:5,rinse:0},
    {name:"Zanetti Injector 3",type:"direct",flow:1,product:"",solution:400,preflow:5,rinse:0},
    {name:"Zanetti Flush",type:"flush",flow:0,product:"",solution:0,preflow:5,rinse:10}
  ],
  Menso:[
    {name:"Menso Agitator",type:"vat",flow:10.5,product:"Calcium Nitrate",solution:1500,preflow:5,rinse:45},
    {name:"Menso Fertigation 1",type:"direct",flow:11,product:"Cal 40",solution:100,preflow:5,rinse:0},
    {name:"Menso Fertigation 2",type:"direct",flow:3.7,product:"Optical AG",solution:100,preflow:5,rinse:0},
    {name:"Menso Flush",type:"flush",flow:0,product:"",solution:0,preflow:5,rinse:10}
  ],
  Strathdee:[
    {name:"Strathdee Injector 1",type:"vat",flow:10,product:"Calcium Nitrate",solution:1500,preflow:5,rinse:30},
    {name:"Strathdee Agitator 1",type:"direct",flow:5,product:"",solution:420,preflow:5,rinse:0},
    {name:"Strathdee Injector 2",type:"direct",flow:10,product:"",solution:420,preflow:5,rinse:0},
    {name:"Strathdee Flush",type:"flush",flow:0,product:"",solution:0,preflow:5,rinse:10}
  ],
  "Norris Back":[
    {name:"Norris Injector 1",type:"vat",flow:10.5,product:"Calcium Nitrate",solution:1000,preflow:5,rinse:30},
    {name:"Norris Injector 2",type:"direct",flow:6.2,product:"Optical AG",solution:80,preflow:5,rinse:0},
    {name:"Norris Injector 3",type:"direct",flow:3.8,product:"",solution:0,preflow:5,rinse:0},
    {name:"Norris Flush",type:"flush",flow:0,product:"",solution:0,preflow:5,rinse:10}
  ]
};
function products(){let a=Array.isArray(saved.fertilizers)?saved.fertilizers.slice():["Calcium Nitrate","Potassium Sulphate"];["Calcium Nitrate","Cal 40","Optical AG","KS 32"].forEach(x=>{if(!a.includes(x))a.push(x)});return a}
function meta(name){const m=saved.productMeta?.[name]||{},n=name.toLowerCase();if(m.method)return m;return {method:(n==="cal 40"||n==="optical ag")?"direct":"mixed",unit:(n==="cal 40"||n==="optical ag"||n==="ks 32")?"L/ha":"kg/ha",bagSize:n==="calcium nitrate"?25:0}}
function defaultType(i){return i===0?"vat":"direct"}
function cfg(){const farm=$("farm").value,base=EXCEL_PRESETS[farm]||saved.injectorConfig?.[farm]||[],custom=qsetup[farm]||[];return [0,1,2,3].map(i=>{const b=base[i]||{},c=custom[i]||{};return {name:c.name??b.name??`Injector ${i+1}`,flow:Number(c.flow??b.flow)||0,type:c.type||b.type||defaultType(i),product:c.product??b.product??(i===0?"Calcium Nitrate":""),solution:Number(c.solution??b.solution)||1500,preflow:Math.max(5,Number(c.preflow??b.preflow)||5),rinse:Number(c.rinse??b.rinse??b.finalVatRinseMinutes)||0}})}
function saveSetup(){localStorage.setItem(QKEY,JSON.stringify(qsetup))}
function renderSetup(){const farm=$("farm").value,c=cfg();$("setupInjectors").innerHTML=c.map((x,i)=>`<div class="setupInj" data-i="${i}"><strong>Injector ${i+1}</strong><div class="two"><div><label>Name</label><input class="sname" value="${x.name}"></div><div><label>Type</label><select class="stype"><option value="vat" ${x.type==="vat"?"selected":""}>Prepared vat</option><option value="direct" ${x.type==="direct"?"selected":""}>Direct injection</option><option value="flush" ${x.type==="flush"?"selected":""}>Flush / rinse</option></select></div></div><div class="two"><div><label>Flow rate (L/min)</label><input class="sflow" type="number" min="0" step="0.1" value="${x.flow||""}"></div><div><label>Default product</label><select class="sproduct"><option value="">Choose when planning</option>${products().map(p=>`<option ${x.product===p?"selected":""}>${p}</option>`).join("")}</select></div></div><div class="setupVat"><div class="two"><div><label>Default vat volume (L)</label><input class="ssolution" type="number" min="0" value="${x.solution}"></div><div><label>Final rinse (min)</label><input class="srinse" type="number" min="0" value="${x.rinse}"></div></div></div><label>Minimum preflow (min)</label><input class="spreflow" type="number" min="5" value="${x.preflow}"></div>`).join("");document.querySelectorAll(".setupInj").forEach(d=>{const i=Number(d.dataset.i),sync=()=>{qsetup[farm]??=[];qsetup[farm][i]={name:d.querySelector(".sname").value.trim()||`Injector ${i+1}`,type:d.querySelector(".stype").value,flow:Number(d.querySelector(".sflow").value)||0,product:d.querySelector(".sproduct").value,solution:Number(d.querySelector(".ssolution").value)||1500,preflow:Math.max(5,Number(d.querySelector(".spreflow").value)||5),rinse:Number(d.querySelector(".srinse").value)||0};saveSetup();d.querySelector(".setupVat").style.display=d.querySelector(".stype").value==="vat"?"block":"none";renderInjectors();recalc()};d.querySelector(".setupVat").style.display=d.querySelector(".stype").value==="vat"?"block":"none";d.querySelectorAll("input,select").forEach(el=>el.onchange=sync)})}
function area(){return [...chosen].reduce((s,o)=>s+(FARMS[$("farm").value]?.[o]||0),0)}
function fmtMin(m){m=Math.max(0,Math.round(Number(m)||0));return `${String(Math.floor(m/60)).padStart(2,"0")}:${String(m%60).padStart(2,"0")}`}
function renderOutlets(){chosen.clear();injectionOrder=[];$("outlets").innerHTML=Object.entries(FARMS[$("farm").value]).map(([o,h])=>`<button class="outlet" data-o="${o}">${o}<small>${h.toFixed(2)} ha</small></button>`).join("");document.querySelectorAll(".outlet").forEach(b=>b.onclick=()=>{chosen.has(b.dataset.o)?chosen.delete(b.dataset.o):chosen.add(b.dataset.o);b.classList.toggle("on");recalc()});renderInjectors();recalc()}
function renderInjectors(){injectionOrder=[];const c=cfg();$("injectors").innerHTML=c.map((x,i)=>{const isVat=x.type==="vat",isFlush=x.type==="flush",prod=x.product||products()[0];if(isFlush)return `<div class="inj flushOnly" data-i="${i}"><div class="injHead"><strong>${x.name}</strong><button class="toggle">Use</button></div><div class="injBody"><div class="two"><div><label>Flush runtime (min)</label><input class="rinse" type="number" min="0" value="${x.rinse||10}"></div><div><label>Preflow (min)</label><input class="preflow" type="number" min="5" value="${x.preflow}"></div></div><div class="calc">Fresh-water flush / rinse</div></div></div>`;return `<div class="inj" data-i="${i}" data-type="${x.type}"><div class="injHead"><strong>${x.name}</strong><button class="toggle">Use</button></div><div class="injBody"><div class="two"><div><label>Product</label><select class="product"><option value="">Select product</option>${products().map(p=>`<option ${prod===p?"selected":""}>${p}</option>`).join("")}</select></div><div><label>Flow rate (L/min)</label><input class="flow" type="number" value="${x.flow||""}" readonly></div></div><div class="two"><div><label>Rate</label><input class="rate" type="number" min="0" step="0.1" value="40"></div><div><label>Rate unit</label><select class="unit"><option>kg/ha</option><option>L/ha</option></select></div></div>${isVat?`<div class="solutionWrap"><label>Prepared vat / solution volume (L)</label><input class="solution" type="number" min="0" value="${x.solution}"></div>`:""}<div class="two"><div><label>Preflow (min)</label><input class="preflow" type="number" min="5" value="${x.preflow}"></div>${isVat?`<div><label>Final rinse (min)</label><input class="rinse" type="number" min="0" value="${x.rinse}"></div>`:`<input class="rinse" type="hidden" value="0">`}</div><div class="calc"></div></div></div>`}).join("");document.querySelectorAll(".inj").forEach(d=>{d.querySelector(".toggle").onclick=()=>{d.classList.toggle("active");d.querySelector(".toggle").classList.toggle("on");d.querySelector(".toggle").textContent=d.classList.contains("active")?"Using":"Use";const i=Number(d.dataset.i);if(d.classList.contains("active")){if(!injectionOrder.includes(i))injectionOrder.push(i)}else injectionOrder=injectionOrder.filter(x=>x!==i);recalc()};d.querySelectorAll("input,select").forEach(x=>x.oninput=()=>recalc());const pr=d.querySelector(".product");if(pr){pr.onchange=()=>{setMethod(d);recalc()};setMethod(d)}})}
function setMethod(d){const p=d.querySelector(".product").value;if(!p)return;const m=meta(p);d.querySelector(".unit").value=m.unit||"kg/ha"}
function injCalc(d){const type=d.dataset.type||"direct",product=d.querySelector(".product")?.value||"Fresh water",m=meta(product),flow=Number(d.querySelector(".flow")?.value)||0,rate=Number(d.querySelector(".rate")?.value)||0,unit=d.querySelector(".unit")?.value||"L/ha",a=area(),qty=a*rate,solution=Number(d.querySelector(".solution")?.value)||0,pre=Math.max(5,Number(d.querySelector(".preflow").value)||5),rinse=Math.max(0,Number(d.querySelector(".rinse").value)||0);d.querySelector(".preflow").value=pre;if(type==="flush")return{product,method:"flush",unit,qty:0,solution:0,flow:1,pre,rinse,runtime:rinse,total:rinse};let litres=type==="vat"?solution:(unit==="L/ha"?qty:qty);let runtime=flow>0&&litres>0?Math.ceil(litres/flow):0;return{product,method:type,unit,qty,solution,flow,pre,rinse,runtime,total:runtime+rinse}}
function moveInjector(i,dir){const pos=injectionOrder.indexOf(i),np=pos+dir;if(pos<0||np<0||np>=injectionOrder.length)return;[injectionOrder[pos],injectionOrder[np]]=[injectionOrder[np],injectionOrder[pos]];recalc()}
function recalc(){const a=area();$("area").textContent=`${a.toFixed(2)} ha`;$("selectedText").textContent=chosen.size?[...chosen].join(", "):"No outlets";const byIndex={};document.querySelectorAll(".inj").forEach(d=>{if(!d.classList.contains("active"))return;const x=injCalc(d),calc=d.querySelector(".calc"),i=Number(d.dataset.i);let qty=x.qty.toFixed(1)+" "+(x.unit==="kg/ha"?"kg":"L");if(x.method==="vat"&&x.product.toLowerCase()==="calcium nitrate"){const bs=Number(meta(x.product).bagSize)||25,bags=bs?Math.ceil(x.qty/bs):0;qty+=` · ${bags} × ${bs} kg bags = ${bags*bs} kg mixed`};calc.innerHTML=`Required: <strong>${qty}</strong><br>${x.method==="vat"?`Prepared solution: ${x.solution.toFixed(0)} L · `:""}Runtime: <strong>${x.flow?x.runtime+" min":"Flow rate needed"}</strong>${x.rinse?` · final flush ${x.rinse} min`:""}`;byIndex[i]={i,name:d.querySelector(".injHead strong").textContent,...x}});injectionOrder=injectionOrder.filter(i=>byIndex[i]);Object.keys(byIndex).map(Number).forEach(i=>{if(!injectionOrder.includes(i))injectionOrder.push(i)});const lines=injectionOrder.map(i=>byIndex[i]).filter(Boolean);const main=Number($("mainRuntime").value)||0;let html=`<div class="aquaHead">${$("farm").value}${chosen.size?` · Outlets ${[...chosen].join(", ")}`:""}</div><div class="aquaLine"><span>Main Runtime</span><b>${main} min</b></div>`;if(!chosen.size)html+=`<p class="warning">Select at least one outlet.</p>`;if(lines.length>1){html+=`<div class="orderTitle">Injection order</div>`;lines.forEach((x,pos)=>{html+=`<div class="orderRow"><b>${pos+1}</b><span>${x.name}<small>${x.product}</small></span><button ${pos===0?"disabled":""} onclick="moveInjector(${x.i},-1)" aria-label="Move up">↑</button><button ${pos===lines.length-1?"disabled":""} onclick="moveInjector(${x.i},1)" aria-label="Move down">↓</button></div>`})}if(lines.length){let cursor=lines[0].pre;html+=`<table class="aquaTable"><thead><tr><th>Injector</th><th class="num">Runtime</th><th class="num">Pre/Flow</th></tr></thead><tbody>`;lines.forEach((x,pos)=>{html+=`<tr><td><strong>${x.name}</strong><small>${x.product}</small></td><td class="num">${x.flow?x.runtime:"—"}</td><td class="num">${x.flow?cursor:"—"}</td></tr>`;if(x.flow)cursor+=x.runtime});const flush=lines.findLast?lines.findLast(x=>x.rinse>0):[...lines].reverse().find(x=>x.rinse>0);if(flush){html+=`<tr><td><strong>${$("farm").value} Flush</strong><small>Final fresh-water rinse</small></td><td class="num">${flush.rinse}</td><td class="num">${cursor}</td></tr>`}html+=`</tbody></table><p class="aquaNote">Runtime and Pre/Flow are shown as whole minutes for direct entry into AquaLink.</p>`}else html+=`<p class="hint">No injection pumps selected — water only.</p>`;$("result").innerHTML=html}
function runtimeOptions(){let s="";for(let m=60;m<=720;m+=15)s+=`<option value="${m}" ${m===360?"selected":""}>${fmtMin(m)}</option>`;$("mainRuntime").innerHTML=s}
function init(){runtimeOptions();$("farm").innerHTML=Object.keys(FARMS).map(f=>`<option>${f}</option>`).join("");$("farm").value="Menso";$("farm").onchange=()=>{renderSetup();renderOutlets()};$("mainRuntime").onchange=recalc;document.querySelectorAll(".runtimeMini button").forEach(b=>b.onclick=()=>{let v=Number($("mainRuntime").value)+Number(b.dataset.min);v=Math.max(60,Math.min(720,v));$("mainRuntime").value=v;recalc()});$("clear").onclick=()=>renderOutlets();$("setupToggle").onclick=()=>{const p=$("setupPanel"),open=p.classList.toggle("open");$("setupToggle").querySelector("b").textContent=open?"Hide":"Show"};$("copy").onclick=async()=>{const text=$("result").innerText;try{await navigator.clipboard.writeText(text);$("copy").textContent="Copied ✓";setTimeout(()=>$("copy").textContent="Copy AquaLink Summary",1200)}catch(e){alert(text)}};renderSetup();renderOutlets()};init();
